///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MessageModelMessages {
/*
{
  "mID": 12,
  "mDetail": "slm",
  "senderID": 1
} 
*/

  int? mID;
  String? mDetail;
  int? senderID;

  MessageModelMessages({
    this.mID,
    this.mDetail,
    this.senderID,
  });
  MessageModelMessages.fromJson(Map<String, dynamic> json) {
    mID = json['mID']?.toInt();
    mDetail = json['mDetail']?.toString();
    senderID = json['senderID']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['mID'] = mID;
    data['mDetail'] = mDetail;
    data['senderID'] = senderID;
    return data;
  }
}

class MessageModel {
/*
{
  "id": 1,
  "name": "Kişi 1",
  "image": "https://genshin.honeyhunterworld.com/img/kazuha_047.webp",
  "messages": [
    {
      "mID": 12,
      "mDetail": "slm",
      "senderID": 1
    }
  ]
} 
*/

  int? id;
  String? name;
  String? image;
  List<MessageModelMessages?>? messages;

  MessageModel({
    this.id,
    this.name,
    this.image,
    this.messages,
  });
  MessageModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    image = json['image']?.toString();
    if (json['messages'] != null) {
      final v = json['messages'];
      final arr0 = <MessageModelMessages>[];
      v.forEach((v) {
        arr0.add(MessageModelMessages.fromJson(v));
      });
      messages = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    if (messages != null) {
      final v = messages;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['messages'] = arr0;
    }
    return data;
  }
}
